version: '3'

services:
  base:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024

  pubsub:
    image: "redis:alpine"
    ports:
      - "6380:6379"
    sysctls:
      net.core.somaxconn: 1024

  base_with_auth:
    image: "redis:alpine"
    command: redis-server --requirepass some-password
    ports:
      - "16379:6379"
    sysctls:
      net.core.somaxconn: 1024

  sentinel:
    build: ./test/docker/sentinel
    ports:
      - "6381:6381"
      - "6382:6382"
      - "26379:26379"
      - "26380:26380"
      - "26381:26381"
    sysctls:
      net.core.somaxconn: 1024
